/**
 * All user-facing strings in one place.
 * To add a new language, duplicate this object and swap the values.
 * Then wire up a language selector that picks which object to use.
 */
export const Strings = {

  // ─── Navigation ─────────────────────────────────────────────────────────────
  nav: {
    back:     '← Back',
    hint:     'Hint',
    hideHint: 'Hide',
    retry:    'Try Again',
    home:     'Home',
  },

  // ─── Home Screen ─────────────────────────────────────────────────────────────
  home: {
    logoTitle:  'Energia',
    logoSub:    'Finish at zero. Navigate every cell.',
    howToPlay:  'How to Play',
    support:    'Source',
    supportSub: 'Github',
    difficulties: {
      easy:   { label: 'Easy 3×3',   sub: 'Basic tiles' },
      medium: { label: 'Medium 4×4', sub: 'Locks + directions' },
      hard:   { label: 'Hard 4×4',   sub: 'Checkpoints + all types' },
      brutal: { label: 'Brutal 5x5', sub: 'Everything on large scale' },
    },
  },

  // ─── Game Screen ─────────────────────────────────────────────────────────────
  game: {
    idlePrompt:  'Tap any cell to start',
    stuckBanner: '⛔ No valid moves — Undo or Reset',
  },

  // ─── Energy Bar ──────────────────────────────────────────────────────────────
  energyBar: {
    label:          '⚡ ENERGY',
    movesLabel:     'Moves:',
    lowEnergyAlert: '⚠️',
    locked:         (movesLeft: number) => `🔒 ${movesLeft} left`,
    unlocked:       '🔓 Unlocked!',
  },

  // ─── Controls ────────────────────────────────────────────────────────────────
  controls: {
    undo:  'Undo',
    reset: 'Reset',
    regenerate: 'New',
  },

  // ─── Win Screen ──────────────────────────────────────────────────────────────
  win: {
    title:    [
      "Bingo Win!",
      "Grid Conquered!",
      "Puzzle Victory!",
      "Blast Off!",
      "Magic Solve!",
      "Puzzle Master!",
      "Grid On Fire!",
      "Nailed It!",
      "Bullseye Hit!",
      "Star Player!",
      "Cool Move!",
      "Eureka Moment!",
      "Pop Win!",
      "Dance Time!",
      "Slice Winner!"
    ],
    subtitle:   [
      'Perfect path. Zero energy spent wisely.',
      'Flawless! No energy wasted.',
      'You mastered the path with zero excess.',
      'Optimal moves, maximum efficiency!',
      'All energy used perfectly. Well done!',
    ],
    subtitletwo: [
      'Almost perfect. Some energy left behind...',
      'Good job! But can you use all your energy?',
      'Nice path, though a bit of energy remains.',
      'You finished with moves to spare… can you improve?',
      'Some energy left unused. Challenge yourself!',
    ],
    subtitleone: [
      'Energy left wasted. Try to plan better!',
      'Many moves unused. Can you optimize?',
      'Your path is inefficient. Where is the energy?',
      'Finished, but much energy remains. Focus!',
      'Left too much energy behind. Try again!',
    ],
    statMoves:  'Time',
    statGrid:   'Grid',
    statLevel:  'Level',
    playAgain:  'Play Again',
    replay:     'Same Puzzle',
    home:       'Main Menu',
    generate:   'Generate New',
  },

  // ─── How To Screen ───────────────────────────────────────────────────────────
  howTo: {
    title:       'How to Play',
    letsPlay:    "Let's Play!",
    tilesSection: 'Tile Types',
    rules: [
      { icon: '🗺️', text: 'Visit ', highlight: 'every cell', suffix: ' at least once.' },
      { icon: '⚡', text: 'Each move ', highlight: 'costs 1 energy', suffix: ' or more.' },
      { icon: '🧩', text: 'sometimes you ', highlight: 'gain energy', suffix: ' sometimes lose.'  },
      { icon: '🚫', text: 'Energy can ', highlight: 'never go negative', suffix: '.' },
      { icon: '🎯', text: 'Finish with ', highlight: '0 energy', suffix: ' for a perfect score.' },
      { icon: '📊', text: 'Extra energy ', highlight: 'reduces your score', suffix: ' but win is a win.' },
    ],
    tiles: [
      { icon: '+N',  name: 'Positive Tile', desc: 'Adds energy when stepped on.' },
      { icon: '−N',  name: 'Negative Tile', desc: 'Drains energy when stepped on.' },
      { icon: '×N',  name: 'Multiplier',    desc: 'Multiplies your current energy by N.' },
      { icon: '🔒',  name: 'Locked Tile',   desc: 'Blocked until you make enough moves.' },
      { icon: 'in↓', name: 'Entry Gate',    desc: 'Can only be entered from shown direction(s).' },
      { icon: 'ex↑', name: 'Exit Gate',     desc: 'Forces your next move in shown direction(s).' },
      { icon: '≥N',  name: 'Checkpoint',    desc: 'You must arrive here with at least N energy.' },
    ],
  },
  generating: 'Generating',
  funFuctTitle: 'Building takes time, here is a fun fact:',
  funFacts:  [
    "Honey never spoils.",
    "Bananas are berries, but strawberries aren’t.",
    "Octopuses have three hearts.",
    "A group of flamingos is called a “flamboyance.”",
    "Sloths can hold their breath longer than dolphins.",
    "Sea otters hold hands while sleeping.",
    "Cows have best friends.",
    "Some turtles can breathe through their butts.",
    "Wombat poop is cube-shaped.",
    "A day on Venus is longer than a year on Venus.",
    "There’s a species of jellyfish that is immortal.",
    "Pigeons can recognize themselves in mirrors.",
    "Koalas sleep up to 22 hours a day.",
    "A cloud can weigh over a million pounds.",
    "Sharks existed before trees.",
    "Frogs can freeze without dying.",
    "Butterflies taste with their feet.",
    "Sea slugs can eat themselves and regrow.",
    "Your stomach gets a new lining every 3-4 days.",
    "Crows can hold grudges.",
    "There’s a basketball court on top of the US Supreme Court.",
    "The heart of a blue whale is the size of a car.",
    "Wombats can run up to 25 mph.",
    "Penguins propose with pebbles.",
    "Some ants can build living bridges.",
    "Sloths can rotate their heads almost 360°.",
    "Humans share 60% of DNA with bananas.",
    "A jiffy is 1/100th of a second.",
    "There’s a species of fungus that glows in the dark.",
    "Sea cucumbers can shoot out their internal organs to escape predators.",
    "Some frogs can survive being frozen for years.",
    "The Eiffel Tower can grow 15 cm taller in summer.",
    "Koalas have fingerprints almost identical to humans.",
    "Dolphins have names for each other.",
    "There’s a planet made of diamond.",
    "Some turtles can live over 200 years.",
    "Starfish can regrow arms — and some can regenerate their entire body.",
    "A sneeze travels about 100 mph.",
    "Elephants can “hear” with their feet.",
    "Otters have a favorite rock they use to crack shells.",
    "Sea urchins can live over 100 years.",
    "Butterflies can see red, green, and yellow.",
    "A cockroach can live for weeks without a head.",
    "Some fish can walk on land.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Bats always turn left when exiting a cave.",
    "Sharks can detect a drop of blood in an Olympic-sized pool.",
    "A day on Mercury is 58 Earth days long.",
    "Lobsters can live over 100 years.",
    "Sloths can hold their breath for 40 minutes.",
    "There’s a species of bird that can mimic chainsaws.",
    "Some spiders can survive underwater for hours.",
    "Jellyfish have been around for over 500 million years.",
    "Seahorses are the only animals where males give birth.",
    "Your nose can remember 50,000 different scents.",
    "A group of owls is called a parliament.",
    "Dolphins sleep with one eye open.",
    "Some frogs can change color to match their environment.",
    "Cats can make over 100 different sounds.",
    "There’s a species of ant that can enslave other ants.",
    "A single strand of spider silk is stronger than steel.",
    "Flamingos get pink from the food they eat.",
    "Giraffes have no vocal cords.",
    "Some whales can live over 200 years.",
    "Sloths can swim three times faster than they walk.",
    "A group of hedgehogs is called a prickle.",
    "Otters hold hands so they don’t drift apart.",
    "Pigs are smarter than dogs.",
    "Your stomach produces a new layer of mucus every 3 days.",
    "Some turtles can breathe through their cloaca.",
    "The mantis shrimp can punch as fast as a bullet.",
    "Elephants mourn their dead.",
    "Starfish have no brain.",
    "Some fish can recognize faces.",
    "A group of ferrets is called a business.",
    "The heart of a shrimp is located in its head.",
    "Snails can sleep for 3 years.",
    "Polar bears have black skin under their fur.",
    "Seahorses can change color to communicate.",
    "Dogs’ noses are wet to help them absorb scent chemicals.",
    "Some birds can see ultraviolet light.",
    "Elephants can communicate over several miles.",
    "Sea stars can turn their stomachs inside out.",
    "Owls can rotate their heads almost 360°.",
    "Some sharks glow in the dark.",
    "The tongue of a blue whale can weigh as much as an elephant.",
    "Some frogs can survive being frozen solid.",
    "A cow can walk upstairs but not downstairs.",
    "Hummingbirds can fly backward.",
    "Ants never sleep.",
    "There’s a tree that can grow more than 40 different types of fruit.",
    "Some octopuses can mimic other animals.",
    "Elephants can smell water from miles away.",
    "Kangaroos can’t walk backward.",
    "Dolphins have been observed teaching their young to use tools.",
    "Your brain uses 20% of your body’s oxygen.",
    "Some fish can survive out of water for hours.",
    "A group of crows is called a murder.",
    "Some birds sleep while flying.",
    "The fingerprints of a koala are nearly identical to humans.",
    "Sharks have been around longer than trees.",
    "Sloths can rotate their heads almost 360 degrees.",
    "Octopuses have blue blood.",
    "Wombats produce cube-shaped poop.",
    "Bananas float in water because they’re less dense than water.",
    "Some cats are allergic to humans.",
    "Frogs can regrow lost limbs.",
    "Mosquitoes are attracted to the color blue twice as much as to other colors.",
    "A group of ferrets is called a business.",
    "Owls cannot move their eyeballs.",
    "A day on Uranus lasts 17 hours 14 minutes.",
    "Some turtles can breathe through their butts during hibernation.",
    "Butterflies can see red, green, and yellow.",
    "Penguins propose with pebbles.",
    "Sloths can hold their breath longer than dolphins.",
    "Dolphins have names for each other.",
    "Elephants are the only animals that can’t jump.",
    "Some spiders can survive being submerged underwater for hours.",
    "The unicorn is the national animal of Scotland.",
    "A snail can sleep for three years.",
    "Otters hold hands while sleeping.",
    "The mantis shrimp can punch as fast as a bullet.",
    "A group of flamingos is called a flamboyance.",
    "Cows have best friends.",
    "Some birds can mimic chainsaws.",
    "The heart of a blue whale is the size of a car.",
    "There’s a species of jellyfish that is immortal.",
    "Sloths can rotate their heads almost 360°.",
    "Koalas have fingerprints similar to humans.",
    "A cloud can weigh over a million pounds.",
    "Sharks can detect a drop of blood in an Olympic pool.",
    "Sea cucumbers can shoot out their internal organs to escape predators.",
    "Your stomach lining renews every 3-4 days.",
    "Elephants can communicate over miles.",
    "Bats always turn left when leaving a cave.",
    "Crows can hold grudges against humans.",
    "Honey never spoils.",
    "Bananas are berries, but strawberries aren’t.",
    "Some spiders survive underwater for hours.",
    "Crows can hold grudges against humans.",
    "Sloths can rotate their heads almost 360°."
]

} as const;