/**
 * All user-facing strings in one place.
 * Supports multiple languages.
 */
export type Language = 'en' | 'es' | 'fr' | 'ru';

const englishStrings = {

  // ─── Navigation ─────────────────────────────────────────────────────────────
  nav: {
    back:     '← Back',
    hint:     'Hint',
    hideHint: 'Hide',
    retry:    'Try Again',
    home:     'Home',
  },

  // ─── Home Screen ─────────────────────────────────────────────────────────────
  home: {
    logoTitle:  'Energia',
    logoSub:    'Finish at zero. Navigate every cell.',
    howToPlay:  'Manual',
    tutorial:   'Tutorial',
    support:    'Source',
    supportSub: 'Github',
    difficulties: {
      easy:   { label: 'Easy 3×3',   sub: 'Basic tiles' },
      medium: { label: 'Medium 4×4', sub: 'Locks + directions' },
      hard:   { label: 'Hard 4×4',   sub: 'Checkpoints + all types' },
      brutal: { label: 'Brutal 5x5', sub: 'Everything on large scale' },
    },
  },

  // ─── Game Screen ─────────────────────────────────────────────────────────────
  game: {
    idlePrompt:  'Tap any cell to start',
    stuckBanner: '⛔ No valid moves — Undo or Reset',
  },

  // ─── Tutorial Mode ───────────────────────────────────────────────────────────
  tutorial: {
    title:       'Tutorial',
    tooltips: {
      startRule:     'Start on a positive tile to gain energy.',
      secondRule:    'You can visit only neighbours.',
      thirdRule:     'Any move costs 1 energy.',
      fourthrule:    'Ping Indicates your location.',
      multiplier:    '✕ Multiplier tiles multiply your current energy',
      drain:         '⬇ Negative tiles drain energy. Be careful!',
      locked:        '🔒 Locked tiles unlock after enough moves',
      allTiles:      '✓ Visit every single tile to complete the puzzle',
      finish:        'Finish on zero energy for a perfect score.',
      completed:     '🎉 Great! You completed the tutorial!',
    },
  },

  // ─── Energy Bar ──────────────────────────────────────────────────────────────
  energyBar: {
    label:          '⚡ ENERGY',
    movesLabel:     'Moves:',
    lowEnergyAlert: '⚠️',
    locked:         (movesLeft: number) => `🔒 ${movesLeft} left`,
    unlocked:       '🔓 Unlocked!',
  },

  // ─── Controls ────────────────────────────────────────────────────────────────
  controls: {
    undo:       'Undo',
    reset:      'Reset',
    regenerate: 'New',
  },

  // ─── Win Screen ──────────────────────────────────────────────────────────────
  win: {
    title: [
      "Bingo Win!",
      "Grid Conquered!",
      "Puzzle Victory!",
      "Blast Off!",
      "Magic Solve!",
      "Puzzle Master!",
      "Grid On Fire!",
      "Nailed It!",
      "Bullseye Hit!",
      "Star Player!",
      "Cool Move!",
      "Eureka Moment!",
      "Pop Win!",
      "Dance Time!",
      "Slice Winner!"
    ],
    subtitle: [
      'Perfect path. Zero energy spent wisely.',
      'Flawless! No energy wasted.',
      'You mastered the path with zero excess.',
      'Optimal moves, maximum efficiency!',
      'All energy used perfectly. Well done!',
    ],
    subtitletwo: [
      'Almost perfect. Some energy left behind...',
      'Good job! But can you use all your energy?',
      'Nice path, though a bit of energy remains.',
      'You finished with moves to spare… can you improve?',
      'Some energy left unused. Challenge yourself!',
    ],
    subtitleone: [
      'Energy left wasted. Try to plan better!',
      'Many moves unused. Can you optimize?',
      'Your path is inefficient. Where is the energy?',
      'Finished, but much energy remains. Focus!',
      'Left too much energy behind. Try again!',
    ],
    statMoves:  'Time',
    statGrid:   'Grid',
    statLevel:  'Level',
    playAgain:  'Play Again',
    replay:     'Same Puzzle',
    home:       'Main Menu',
    generate:   'Generate New',
  },

  // ─── How To Screen ───────────────────────────────────────────────────────────
  howTo: {
    title:    'How to Play',
    letsPlay: "Let's Play!",
    tilesSection: 'Tile Types',
    rules: [
      { icon: '🗺️', text: 'Visit ',    highlight: 'every cell',      suffix: ' at least once.' },
      { icon: '⚡', text: 'Each move ', highlight: 'costs 1 energy',  suffix: ' or more.' },
      { icon: '🧩', text: 'sometimes you ', highlight: 'gain energy', suffix: ' sometimes lose.' },
      { icon: '🚫', text: 'Energy can ', highlight: 'never go negative', suffix: '.' },
      { icon: '🎯', text: 'Finish with ', highlight: '0 energy',      suffix: ' for a perfect score.' },
      { icon: '📊', text: 'Extra energy ', highlight: 'reduces your score', suffix: ' but win is a win.' },
    ],
    tiles: [
      { icon: '+N',  name: 'Positive Tile', desc: 'Adds energy when stepped on.' },
      { icon: '−N',  name: 'Negative Tile', desc: 'Drains energy when stepped on.' },
      { icon: '×N',  name: 'Multiplier',    desc: 'Multiplies your current energy by N.' },
      { icon: '🔒',  name: 'Locked Tile',   desc: 'Blocked until you make enough moves.' },
      { icon: 'in↓', name: 'Entry Gate',    desc: 'Can only be entered from shown direction(s).' },
      { icon: 'ex↑', name: 'Exit Gate',     desc: 'Forces your next move in shown direction(s).' },
      { icon: '≥N',  name: 'Checkpoint',    desc: 'You must arrive here with at least N energy.' },
    ],
  },
  generating:    'Generating',
  funFactTitle:  'Building takes time, here is a fun fact:',
  funFacts: [
    "Honey never spoils.",
    "Bananas are berries, but strawberries aren't.",
    "Octopuses have three hearts.",
    "A group of flamingos is called a \"flamboyance.\"",
    "Sloths can hold their breath longer than dolphins.",
    "Sea otters hold hands while sleeping.",
    "Cows have best friends.",
    "Some turtles can breathe through their butts.",
    "Wombat poop is cube-shaped.",
    "A day on Venus is longer than a year on Venus.",
    "There's a species of jellyfish that is immortal.",
    "Pigeons can recognize themselves in mirrors.",
    "Koalas sleep up to 22 hours a day.",
    "A cloud can weigh over a million pounds.",
    "Sharks existed before trees.",
    "Frogs can freeze without dying.",
    "Butterflies taste with their feet.",
    "Sea slugs can eat themselves and regrow.",
    "Your stomach gets a new lining every 3-4 days.",
    "Crows can hold grudges.",
    "There's a basketball court on top of the US Supreme Court.",
    "The heart of a blue whale is the size of a car.",
    "Wombats can run up to 25 mph.",
    "Penguins propose with pebbles.",
    "Some ants can build living bridges.",
    "Sloths can rotate their heads almost 360°.",
    "Humans share 60% of DNA with bananas.",
    "A jiffy is 1/100th of a second.",
    "There's a species of fungus that glows in the dark.",
    "Sea cucumbers can shoot out their internal organs to escape predators.",
    "Some frogs can survive being frozen for years.",
    "The Eiffel Tower can grow 15 cm taller in summer.",
    "Koalas have fingerprints almost identical to humans.",
    "Dolphins have names for each other.",
    "There's a planet made of diamond.",
    "Some turtles can live over 200 years.",
    "Starfish can regrow arms — and some can regenerate their entire body.",
    "A sneeze travels about 100 mph.",
    "Elephants can \"hear\" with their feet.",
    "Otters have a favorite rock they use to crack shells.",
    "Sea urchins can live over 100 years.",
    "Butterflies can see red, green, and yellow.",
    "A cockroach can live for weeks without a head.",
    "Some fish can walk on land.",
    "There are more trees on Earth than stars in the Milky Way.",
    "Bats always turn left when exiting a cave.",
    "Sharks can detect a drop of blood in an Olympic-sized pool.",
    "A day on Mercury is 58 Earth days long.",
    "Lobsters can live over 100 years.",
    "Sloths can hold their breath for 40 minutes.",
    "There's a species of bird that can mimic chainsaws.",
    "Some spiders can survive underwater for hours.",
    "Jellyfish have been around for over 500 million years.",
    "Seahorses are the only animals where males give birth.",
    "Your nose can remember 50,000 different scents.",
    "A group of owls is called a parliament.",
    "Dolphins sleep with one eye open.",
    "Some frogs can change color to match their environment.",
    "Cats can make over 100 different sounds.",
    "There's a species of ant that can enslave other ants.",
    "A single strand of spider silk is stronger than steel.",
    "Flamingos get pink from the food they eat.",
    "Giraffes have no vocal cords.",
    "Some whales can live over 200 years.",
    "Sloths can swim three times faster than they walk.",
    "A group of hedgehogs is called a prickle.",
    "Otters hold hands so they don't drift apart.",
    "Pigs are smarter than dogs.",
    "Your stomach produces a new layer of mucus every 3 days.",
    "Some turtles can breathe through their cloaca.",
    "The mantis shrimp can punch as fast as a bullet.",
    "Elephants mourn their dead.",
    "Starfish have no brain.",
    "Some fish can recognize faces.",
    "A group of ferrets is called a business.",
    "The heart of a shrimp is located in its head.",
    "Snails can sleep for 3 years.",
    "Polar bears have black skin under their fur.",
    "Seahorses can change color to communicate.",
    "Dogs' noses are wet to help them absorb scent chemicals.",
    "Some birds can see ultraviolet light.",
    "Elephants can communicate over several miles.",
    "Sea stars can turn their stomachs inside out.",
    "Owls can rotate their heads almost 360°.",
    "Some sharks glow in the dark.",
    "The tongue of a blue whale can weigh as much as an elephant.",
    "Some frogs can survive being frozen solid.",
    "A cow can walk upstairs but not downstairs.",
    "Hummingbirds can fly backward.",
    "Ants never sleep.",
    "There's a tree that can grow more than 40 different types of fruit.",
    "Some octopuses can mimic other animals.",
    "Elephants can smell water from miles away.",
    "Kangaroos can't walk backward.",
    "Dolphins have been observed teaching their young to use tools.",
    "Your brain uses 20% of your body's oxygen.",
    "Some fish can survive out of water for hours.",
    "A group of crows is called a murder.",
    "Some birds sleep while flying.",
    "The fingerprints of a koala are nearly identical to humans.",
    "Sharks have been around longer than trees.",
    "Sloths can rotate their heads almost 360 degrees.",
    "Octopuses have blue blood.",
    "Wombats produce cube-shaped poop.",
    "Bananas float in water because they're less dense than water.",
    "Some cats are allergic to humans.",
    "Frogs can regrow lost limbs.",
    "Mosquitoes are attracted to the color blue twice as much as to other colors.",
    "A group of ferrets is called a business.",
    "Owls cannot move their eyeballs.",
    "A day on Uranus lasts 17 hours 14 minutes.",
    "Some turtles can breathe through their butts during hibernation.",
    "Butterflies can see red, green, and yellow.",
    "Penguins propose with pebbles.",
    "Sloths can hold their breath longer than dolphins.",
    "Dolphins have names for each other.",
    "Elephants are the only animals that can't jump.",
    "Some spiders can survive being submerged underwater for hours.",
    "The unicorn is the national animal of Scotland.",
    "A snail can sleep for three years.",
    "Otters hold hands while sleeping.",
    "The mantis shrimp can punch as fast as a bullet.",
    "A group of flamingos is called a flamboyance.",
    "Cows have best friends.",
    "Some birds can mimic chainsaws.",
    "The heart of a blue whale is the size of a car.",
    "There's a species of jellyfish that is immortal.",
    "Sloths can rotate their heads almost 360°.",
    "Koalas have fingerprints similar to humans.",
    "A cloud can weigh over a million pounds.",
    "Sharks can detect a drop of blood in an Olympic pool.",
    "Sea cucumbers can shoot out their internal organs to escape predators.",
    "Your stomach lining renews every 3-4 days.",
    "Elephants can communicate over miles.",
    "Bats always turn left when leaving a cave.",
    "Crows can hold grudges against humans.",
    "Honey never spoils.",
    "Bananas are berries, but strawberries aren't.",
    "Some spiders survive underwater for hours.",
    "Crows can hold grudges against humans.",
    "Sloths can rotate their heads almost 360°.",
  ],

} as const;

// ─── Spanish ──────────────────────────────────────────────────────────────────
const spanishStrings = {
  ...englishStrings,
  nav: {
    back:     '← Atrás',
    hint:     'Pista',
    hideHint: 'Ocultar',
    retry:    'Intentar de nuevo',
    home:     'Inicio',
  },
  home: {
    logoTitle:  'Energía',
    logoSub:    'Termina en cero. Navega cada celda.',
    howToPlay:  'Manual',
    tutorial:   'Tutorial',
    support:    'Fuente',
    supportSub: 'Github',
    difficulties: {
      easy:   { label: 'Fácil 3×3',    sub: 'Fichas básicas' },
      medium: { label: 'Medio 4×4',    sub: 'Cerraduras + direcciones' },
      hard:   { label: 'Difícil 4×4',  sub: 'Puntos de control + todos los tipos' },
      brutal: { label: 'Brutal 5×5',   sub: 'Todo a gran escala' },
    },
  },
  game: {
    idlePrompt:  'Toca cualquier celda para empezar',
    stuckBanner: '⛔ Sin movimientos válidos — Deshacer o Reiniciar',
  },
  tutorial: {
    title: 'Tutorial',
    tooltips: {
      startRule:  'Empieza en una ficha positiva para ganar energía.',
      secondRule: 'Solo puedes visitar las celdas vecinas.',
      thirdRule:  'Cualquier movimiento cuesta 1 de energía.',
      fourthrule: 'El ping indica tu ubicación.',
      multiplier: '✕ Las fichas multiplicadoras multiplican tu energía actual',
      drain:      '⬇ Las fichas negativas drenan energía. ¡Ten cuidado!',
      locked:     '🔒 Las fichas bloqueadas se desbloquean tras suficientes movimientos',
      allTiles:   '✓ Visita todas las fichas para completar el puzzle',
      finish:     'Termina con cero de energía para una puntuación perfecta.',
      completed:  '🎉 ¡Genial! ¡Completaste el tutorial!',
    },
  },
  energyBar: {
    label:          '⚡ ENERGÍA',
    movesLabel:     'Movimientos:',
    lowEnergyAlert: '⚠️',
    locked:         (movesLeft: number) => `🔒 ${movesLeft} restantes`,
    unlocked:       '🔓 ¡Desbloqueado!',
  },
  controls: {
    undo:       'Deshacer',
    reset:      'Reiniciar',
    regenerate: 'Nuevo',
  },
  win: {
    title: [
      "¡Bingo!",
      "¡Cuadrícula conquistada!",
      "¡Victoria en el puzzle!",
      "¡Al infinito!",
      "¡Solución mágica!",
      "¡Maestro del puzzle!",
      "¡Cuadrícula en llamas!",
      "¡Clavado!",
      "¡En el blanco!",
      "¡Estrella del juego!",
      "¡Gran jugada!",
      "¡Momento eureka!",
      "¡Ganaste!",
      "¡A bailar!",
      "¡Campeón!"
    ],
    subtitle: [
      'Camino perfecto. Cero energía aprovechada al máximo.',
      '¡Impecable! Sin desperdiciar energía.',
      'Dominaste el camino sin excesos.',
      '¡Movimientos óptimos, eficiencia máxima!',
      '¡Toda la energía usada perfectamente. Bien hecho!',
    ],
    subtitletwo: [
      'Casi perfecto. Algo de energía quedó atrás...',
      '¡Buen trabajo! ¿Pero puedes usar toda la energía?',
      'Buen camino, aunque queda algo de energía.',
      'Terminaste con movimientos de sobra… ¿puedes mejorar?',
      'Quedó algo de energía sin usar. ¡Supérate!',
    ],
    subtitleone: [
      '¡Energía desperdiciada. Intenta planear mejor!',
      'Muchos movimientos sin usar. ¿Puedes optimizar?',
      'Tu camino es ineficiente. ¿Dónde está la energía?',
      'Terminaste, pero queda mucha energía. ¡Concéntrate!',
      'Dejaste demasiada energía atrás. ¡Inténtalo de nuevo!',
    ],
    statMoves:  'Tiempo',
    statGrid:   'Cuadrícula',
    statLevel:  'Nivel',
    playAgain:  'Jugar de nuevo',
    replay:     'Mismo puzzle',
    home:       'Menú principal',
    generate:   'Generar nuevo',
  },
  howTo: {
    title:        '¿Cómo jugar?',
    letsPlay:     '¡A jugar!',
    tilesSection: 'Tipos de fichas',
    rules: [
      { icon: '🗺️', text: 'Visita ',       highlight: 'cada celda',            suffix: ' al menos una vez.' },
      { icon: '⚡', text: 'Cada movimiento ', highlight: 'cuesta 1 de energía', suffix: ' o más.' },
      { icon: '🧩', text: 'A veces ',       highlight: 'ganas energía',         suffix: ' y a veces pierdes.' },
      { icon: '🚫', text: 'La energía ',    highlight: 'nunca puede ser negativa', suffix: '.' },
      { icon: '🎯', text: 'Termina con ',   highlight: '0 de energía',          suffix: ' para una puntuación perfecta.' },
      { icon: '📊', text: 'La energía extra ', highlight: 'reduce tu puntuación', suffix: ', pero ganar es ganar.' },
    ],
    tiles: [
      { icon: '+N',  name: 'Ficha positiva',     desc: 'Añade energía al pisarla.' },
      { icon: '−N',  name: 'Ficha negativa',     desc: 'Drena energía al pisarla.' },
      { icon: '×N',  name: 'Multiplicador',      desc: 'Multiplica tu energía actual por N.' },
      { icon: '🔒',  name: 'Ficha bloqueada',    desc: 'Bloqueada hasta que hagas suficientes movimientos.' },
      { icon: 'in↓', name: 'Puerta de entrada',  desc: 'Solo puede entrarse desde la(s) dirección(es) indicada(s).' },
      { icon: 'ex↑', name: 'Puerta de salida',   desc: 'Obliga a salir en la(s) dirección(es) indicada(s).' },
      { icon: '≥N',  name: 'Punto de control',   desc: 'Debes llegar aquí con al menos N de energía.' },
    ],
  },
  generating:   'Generando',
  funFactTitle: 'La construcción lleva tiempo, aquí va un dato curioso:',
  funFacts: [
    "La miel nunca se echa a perder.",
    "Los plátanos son bayas, pero las fresas no.",
    "Los pulpos tienen tres corazones.",
    "Un grupo de flamencos se llama «flamboyance».",
    "Los perezosos aguantan la respiración más tiempo que los delfines.",
    "Las nutrias marinas se dan la mano mientras duermen.",
    "Las vacas tienen mejores amigos.",
    "Algunas tortugas pueden respirar por sus partes traseras.",
    "Las heces del wombat tienen forma cúbica.",
    "Un día en Venus dura más que un año en Venus.",
    "Existe una especie de medusa inmortal.",
    "Las palomas pueden reconocerse en los espejos.",
    "Los koalas duermen hasta 22 horas al día.",
    "Una nube puede pesar más de 500 000 kg.",
    "Los tiburones existían antes que los árboles.",
    "Las ranas pueden congelarse sin morir.",
    "Las mariposas saborean con los pies.",
    "Las babosas de mar pueden comerse a sí mismas y regenerarse.",
    "Tu estómago renueva su recubrimiento cada 3-4 días.",
    "Los cuervos guardan rencor.",
    "Hay una cancha de baloncesto en la cima del Tribunal Supremo de EE. UU.",
    "El corazón de una ballena azul es del tamaño de un coche.",
    "Los wombats pueden correr hasta 40 km/h.",
    "Los pingüinos piden matrimonio con piedras.",
    "Algunas hormigas pueden construir puentes vivientes.",
    "Los perezosos pueden girar la cabeza casi 360°.",
    "Los humanos compartimos el 60 % de ADN con los plátanos.",
    "Un «jiffy» es 1/100 de segundo.",
    "Existe una especie de hongo que brilla en la oscuridad.",
    "Los pepinos de mar expulsan sus órganos internos para escapar de los depredadores.",
    "Algunas ranas pueden sobrevivir congeladas durante años.",
    "La Torre Eiffel puede crecer 15 cm en verano.",
    "Las huellas digitales del koala son casi idénticas a las humanas.",
    "Los delfines tienen nombres para llamarse entre sí.",
    "Existe un planeta hecho de diamante.",
    "Algunas tortugas pueden vivir más de 200 años.",
    "Las estrellas de mar pueden regenerar sus brazos, y algunas todo su cuerpo.",
    "Un estornudo viaja a unos 160 km/h.",
    "Los elefantes pueden «escuchar» con los pies.",
    "Las nutrias tienen una piedra favorita para romper conchas.",
    "Los erizos de mar pueden vivir más de 100 años.",
    "Las mariposas pueden ver rojo, verde y amarillo.",
    "Una cucaracha puede vivir semanas sin cabeza.",
    "Algunos peces pueden caminar en tierra.",
    "Hay más árboles en la Tierra que estrellas en la Vía Láctea.",
    "Los murciélagos siempre giran a la izquierda al salir de una cueva.",
    "Los tiburones pueden detectar una gota de sangre en una piscina olímpica.",
    "Un día en Mercurio equivale a 58 días terrestres.",
    "Las langostas pueden vivir más de 100 años.",
    "Los perezosos pueden aguantar la respiración 40 minutos.",
    "Existe una especie de pájaro que imita el sonido de las motosierras.",
    "Algunas arañas pueden sobrevivir bajo el agua durante horas.",
    "Las medusas llevan más de 500 millones de años en la Tierra.",
    "Los caballitos de mar son los únicos animales en que el macho da a luz.",
    "Tu nariz puede recordar 50 000 aromas distintos.",
    "Un grupo de búhos se llama «parlamento».",
    "Los delfines duermen con un ojo abierto.",
    "Algunas ranas cambian de color para mimetizarse con el entorno.",
    "Los gatos pueden emitir más de 100 sonidos distintos.",
    "Existe una especie de hormiga que esclaviza a otras hormigas.",
    "Un hilo de seda de araña es más resistente que el acero.",
    "Los flamencos se vuelven rosas por su alimentación.",
    "Las jirafas no tienen cuerdas vocales.",
    "Algunas ballenas pueden vivir más de 200 años.",
    "Los perezosos nadan tres veces más rápido de lo que caminan.",
    "Un grupo de erizos se llama «prickle».",
    "Las nutrias se dan la mano para no separarse.",
    "Los cerdos son más inteligentes que los perros.",
    "Tu estómago produce una nueva capa de mucosa cada 3 días.",
    "Algunas tortugas pueden respirar a través de su cloaca.",
    "El camarón mantis puede golpear tan rápido como una bala.",
    "Los elefantes lloran a sus muertos.",
    "Las estrellas de mar no tienen cerebro.",
    "Algunos peces pueden reconocer caras humanas.",
    "Un grupo de hurones se llama «business».",
    "El corazón del camarón está en su cabeza.",
    "Los caracoles pueden dormir 3 años.",
    "Los osos polares tienen la piel negra bajo su pelaje blanco.",
    "Los caballitos de mar cambian de color para comunicarse.",
    "La nariz húmeda de los perros les ayuda a absorber sustancias odoríferas.",
    "Algunas aves pueden ver la luz ultravioleta.",
    "Los elefantes pueden comunicarse a varios kilómetros de distancia.",
    "Las estrellas de mar pueden invertir su estómago hacia afuera.",
    "Los búhos pueden girar la cabeza casi 360°.",
    "Algunos tiburones brillan en la oscuridad.",
    "La lengua de una ballena azul puede pesar tanto como un elefante.",
    "Algunas ranas sobreviven congeladas por completo.",
    "Una vaca puede subir escaleras pero no bajarlas.",
    "Los colibríes pueden volar hacia atrás.",
    "Las hormigas nunca duermen.",
    "Existe un árbol que puede dar más de 40 tipos de fruta.",
    "Algunos pulpos pueden imitar a otros animales.",
    "Los elefantes pueden oler agua a kilómetros de distancia.",
    "Los canguros no pueden caminar hacia atrás.",
    "Se ha observado a delfines enseñando a sus crías a usar herramientas.",
    "Tu cerebro consume el 20 % del oxígeno de tu cuerpo.",
    "Algunos peces sobreviven fuera del agua durante horas.",
    "Un grupo de cuervos se llama «murder» (asesinato).",
    "Algunas aves duermen mientras vuelan.",
    "Las huellas del koala son casi idénticas a las humanas.",
    "Los tiburones son más antiguos que los árboles.",
    "Los pulpos tienen sangre azul.",
    "Los wombats producen heces en forma de cubo.",
    "Los plátanos flotan en el agua porque son menos densos que ella.",
    "Algunos gatos son alérgicos a los humanos.",
    "Las ranas pueden regenerar extremidades perdidas.",
    "Los mosquitos se sienten atraídos por el azul el doble que por otros colores.",
    "Los búhos no pueden mover los globos oculares.",
    "Un día en Urano dura 17 horas y 14 minutos.",
    "El unicornio es el animal nacional de Escocia.",
    "Un caracol puede dormir tres años.",
    "Las nutrias se toman de la mano mientras duermen.",
    "Los elefantes son los únicos animales que no pueden saltar.",
    "El camarón mantis golpea tan rápido como una bala.",
    "Las vacas tienen mejores amigos.",
  ],
};

// ─── French ───────────────────────────────────────────────────────────────────
const frenchStrings = {
  ...englishStrings,
  nav: {
    back:     '← Retour',
    hint:     'Indice',
    hideHint: 'Masquer',
    retry:    'Réessayer',
    home:     'Accueil',
  },
  home: {
    logoTitle:  'Energia',
    logoSub:    'Terminez à zéro. Naviguez chaque cellule.',
    howToPlay:  'Manuel',
    tutorial:   'Tutoriel',
    support:    'Source',
    supportSub: 'Github',
    difficulties: {
      easy:   { label: 'Facile 3×3',    sub: 'Tuiles de base' },
      medium: { label: 'Moyen 4×4',     sub: 'Verrous + directions' },
      hard:   { label: 'Difficile 4×4', sub: 'Points de contrôle + tous types' },
      brutal: { label: 'Brutal 5×5',    sub: 'Tout à grande échelle' },
    },
  },
  game: {
    idlePrompt:  'Appuyez sur n\'importe quelle cellule pour commencer',
    stuckBanner: '⛔ Aucun mouvement valide — Annuler ou Réinitialiser',
  },
  tutorial: {
    title: 'Tutoriel',
    tooltips: {
      startRule:  'Commencez sur une tuile positive pour gagner de l\'énergie.',
      secondRule: 'Vous ne pouvez visiter que les cellules voisines.',
      thirdRule:  'Tout déplacement coûte 1 point d\'énergie.',
      fourthrule: 'Le ping indique votre position.',
      multiplier: '✕ Les tuiles multiplicatrices multiplient votre énergie actuelle',
      drain:      '⬇ Les tuiles négatives drainent l\'énergie. Attention !',
      locked:     '🔒 Les tuiles verrouillées se débloquent après suffisamment de mouvements',
      allTiles:   '✓ Visitez chaque tuile pour compléter le puzzle',
      finish:     'Terminez avec zéro énergie pour un score parfait.',
      completed:  '🎉 Bravo ! Vous avez terminé le tutoriel !',
    },
  },
  energyBar: {
    label:          '⚡ ÉNERGIE',
    movesLabel:     'Mouvements :',
    lowEnergyAlert: '⚠️',
    locked:         (movesLeft: number) => `🔒 ${movesLeft} restants`,
    unlocked:       '🔓 Déverrouillé !',
  },
  controls: {
    undo:       'Annuler',
    reset:      'Réinitialiser',
    regenerate: 'Nouveau',
  },
  win: {
    title: [
      "Bingo !",
      "Grille conquise !",
      "Victoire !",
      "Décollage !",
      "Résolution magique !",
      "Maître du puzzle !",
      "Grille en feu !",
      "Dans le mille !",
      "En plein cœur !",
      "Joueur d'élite !",
      "Beau mouvement !",
      "Moment eurêka !",
      "Victoire éclatante !",
      "C'est la fête !",
      "Champion !"
    ],
    subtitle: [
      'Chemin parfait. Zéro énergie dépensée avec sagesse.',
      'Impeccable ! Aucune énergie gaspillée.',
      'Vous avez maîtrisé le chemin sans excès.',
      'Mouvements optimaux, efficacité maximale !',
      'Toute l\'énergie utilisée parfaitement. Bravo !',
    ],
    subtitletwo: [
      'Presque parfait. Un peu d\'énergie laissée derrière…',
      'Bon travail ! Mais pouvez-vous utiliser toute votre énergie ?',
      'Beau chemin, bien qu\'il reste un peu d\'énergie.',
      'Vous avez terminé avec des mouvements en réserve… pouvez-vous faire mieux ?',
      'Un peu d\'énergie inutilisée. Dépassez-vous !',
    ],
    subtitleone: [
      'Énergie gaspillée. Essayez de mieux planifier !',
      'Beaucoup de mouvements inutilisés. Pouvez-vous optimiser ?',
      'Votre chemin est inefficace. Où est passée l\'énergie ?',
      'Terminé, mais beaucoup d\'énergie reste. Concentrez-vous !',
      'Trop d\'énergie laissée derrière. Réessayez !',
    ],
    statMoves:  'Temps',
    statGrid:   'Grille',
    statLevel:  'Niveau',
    playAgain:  'Rejouer',
    replay:     'Même puzzle',
    home:       'Menu principal',
    generate:   'Générer nouveau',
  },
  howTo: {
    title:        'Comment jouer',
    letsPlay:     'On joue !',
    tilesSection: 'Types de tuiles',
    rules: [
      { icon: '🗺️', text: 'Visitez ',        highlight: 'chaque cellule',           suffix: ' au moins une fois.' },
      { icon: '⚡', text: 'Chaque mouvement ', highlight: 'coûte 1 énergie',         suffix: ' ou plus.' },
      { icon: '🧩', text: 'Parfois vous ',    highlight: 'gagnez de l\'énergie',     suffix: ', parfois vous en perdez.' },
      { icon: '🚫', text: 'L\'énergie ne ',   highlight: 'peut jamais être négative', suffix: '.' },
      { icon: '🎯', text: 'Terminez avec ',   highlight: '0 énergie',                suffix: ' pour un score parfait.' },
      { icon: '📊', text: 'L\'énergie en trop ', highlight: 'réduit votre score',    suffix: ', mais une victoire reste une victoire.' },
    ],
    tiles: [
      { icon: '+N',  name: 'Tuile positive',    desc: 'Ajoute de l\'énergie lorsqu\'on marche dessus.' },
      { icon: '−N',  name: 'Tuile négative',    desc: 'Draine de l\'énergie lorsqu\'on marche dessus.' },
      { icon: '×N',  name: 'Multiplicateur',    desc: 'Multiplie votre énergie actuelle par N.' },
      { icon: '🔒',  name: 'Tuile verrouillée', desc: 'Bloquée jusqu\'à ce que vous fassiez suffisamment de mouvements.' },
      { icon: 'in↓', name: 'Porte d\'entrée',   desc: 'Ne peut être entrée que depuis la/les direction(s) indiquée(s).' },
      { icon: 'ex↑', name: 'Porte de sortie',   desc: 'Force votre prochain mouvement dans la/les direction(s) indiquée(s).' },
      { icon: '≥N',  name: 'Point de contrôle', desc: 'Vous devez arriver ici avec au moins N d\'énergie.' },
    ],
  },
  generating:   'Génération en cours',
  funFactTitle: 'La construction prend du temps, voici une anecdote amusante :',
  funFacts: [
    "Le miel ne se périme jamais.",
    "Les bananes sont des baies, mais pas les fraises.",
    "Les pieuvres ont trois cœurs.",
    "Un groupe de flamants roses s'appelle une « flamboyance ».",
    "Les paresseux retiennent leur souffle plus longtemps que les dauphins.",
    "Les loutres de mer se tiennent la main en dormant.",
    "Les vaches ont des meilleurs amis.",
    "Certaines tortues respirent par leur postérieur.",
    "Les excréments du wombat sont en forme de cube.",
    "Un jour sur Vénus dure plus longtemps qu'une année sur Vénus.",
    "Il existe une espèce de méduse immortelle.",
    "Les pigeons peuvent se reconnaître dans un miroir.",
    "Les koalas dorment jusqu'à 22 heures par jour.",
    "Un nuage peut peser plus d'un million de kilos.",
    "Les requins existaient avant les arbres.",
    "Les grenouilles peuvent geler sans mourir.",
    "Les papillons goûtent avec leurs pattes.",
    "Les limaces de mer peuvent s'auto-dévorer et se régénérer.",
    "Votre estomac renouvelle sa paroi toutes les 3-4 jours.",
    "Les corbeaux sont rancuniers.",
    "Il y a un terrain de basket au sommet de la Cour suprême des États-Unis.",
    "Le cœur d'une baleine bleue est aussi grand qu'une voiture.",
    "Les wombats peuvent courir à plus de 40 km/h.",
    "Les manchots font leur demande en mariage avec des cailloux.",
    "Certaines fourmis peuvent construire des ponts vivants.",
    "Les paresseux peuvent tourner la tête presque à 360°.",
    "Les humains partagent 60 % de leur ADN avec les bananes.",
    "Un « jiffy » correspond à 1/100e de seconde.",
    "Il existe une espèce de champignon qui brille dans le noir.",
    "Les concombres de mer expulsent leurs organes internes pour échapper aux prédateurs.",
    "Certaines grenouilles survivent à la congélation pendant des années.",
    "La Tour Eiffel peut grandir de 15 cm en été.",
    "Les empreintes digitales des koalas sont presque identiques aux nôtres.",
    "Les dauphins ont des noms pour s'appeler entre eux.",
    "Il existe une planète faite de diamant.",
    "Certaines tortues peuvent vivre plus de 200 ans.",
    "Les étoiles de mer peuvent repousser leurs bras — et certaines régénèrent tout leur corps.",
    "Un éternuement voyage à environ 160 km/h.",
    "Les éléphants peuvent « entendre » avec leurs pattes.",
    "Les loutres ont une pierre favorite pour casser les coquilles.",
    "Les oursins peuvent vivre plus de 100 ans.",
    "Les papillons voient le rouge, le vert et le jaune.",
    "Un cafard peut survivre plusieurs semaines sans tête.",
    "Certains poissons peuvent marcher sur terre.",
    "Il y a plus d'arbres sur Terre que d'étoiles dans la Voie Lactée.",
    "Les chauves-souris tournent toujours à gauche en quittant une grotte.",
    "Les requins détectent une goutte de sang dans une piscine olympique.",
    "Un jour sur Mercure dure 58 jours terrestres.",
    "Les homards peuvent vivre plus de 100 ans.",
    "Les paresseux peuvent retenir leur souffle pendant 40 minutes.",
    "Il existe une espèce d'oiseau qui imite le bruit des tronçonneuses.",
    "Certaines araignées survivent sous l'eau pendant des heures.",
    "Les méduses existent depuis plus de 500 millions d'années.",
    "Les hippocampes sont les seuls animaux où c'est le mâle qui accouche.",
    "Votre nez peut mémoriser 50 000 odeurs différentes.",
    "Un groupe de hiboux s'appelle un « parlement ».",
    "Les dauphins dorment avec un œil ouvert.",
    "Certaines grenouilles changent de couleur pour se camoufler.",
    "Les chats peuvent émettre plus de 100 sons différents.",
    "Il existe une espèce de fourmi qui réduit d'autres fourmis en esclavage.",
    "Un fil de soie d'araignée est plus résistant que l'acier.",
    "Les flamants roses doivent leur couleur à leur alimentation.",
    "Les girafes n'ont pas de cordes vocales.",
    "Certaines baleines peuvent vivre plus de 200 ans.",
    "Les paresseux nagent trois fois plus vite qu'ils ne marchent.",
    "Un groupe de hérissons s'appelle un « prickle ».",
    "Les loutres se tiennent la main pour ne pas dériver.",
    "Les cochons sont plus intelligents que les chiens.",
    "Votre estomac produit une nouvelle couche de mucus toutes les 3 jours.",
    "Certaines tortues respirent via leur cloaque.",
    "La crevette mante peut frapper aussi vite qu'une balle.",
    "Les éléphants pleurent leurs morts.",
    "Les étoiles de mer n'ont pas de cerveau.",
    "Certains poissons reconnaissent les visages humains.",
    "Un groupe de furets s'appelle un « business ».",
    "Le cœur des crevettes se trouve dans leur tête.",
    "Les escargots peuvent dormir 3 ans.",
    "Les ours polaires ont la peau noire sous leur fourrure blanche.",
    "Les hippocampes changent de couleur pour communiquer.",
    "Le nez humide des chiens les aide à capter les molécules odorantes.",
    "Certains oiseaux voient dans l'ultraviolet.",
    "Les éléphants communiquent sur plusieurs kilomètres.",
    "Les étoiles de mer peuvent retourner leur estomac vers l'extérieur.",
    "Les hiboux peuvent pivoter la tête presque à 360°.",
    "Certains requins brillent dans l'obscurité.",
    "La langue d'une baleine bleue peut peser autant qu'un éléphant.",
    "Certaines grenouilles survivent à une congélation complète.",
    "Une vache peut monter un escalier mais pas le descendre.",
    "Les colibris volent en marche arrière.",
    "Les fourmis ne dorment jamais.",
    "Il existe un arbre capable de produire plus de 40 variétés de fruits.",
    "Certaines pieuvres imitent d'autres animaux.",
    "Les éléphants sentent l'eau à des kilomètres de distance.",
    "Les kangourous ne peuvent pas reculer.",
    "Des dauphins ont été observés en train d'enseigner à leurs petits à utiliser des outils.",
    "Votre cerveau consomme 20 % de l'oxygène de votre corps.",
    "Certains poissons survivent hors de l'eau pendant des heures.",
    "Un groupe de corbeaux s'appelle un « meurtre » (murder).",
    "Certains oiseaux dorment en volant.",
    "Les pieuvres ont du sang bleu.",
    "Les wombats produisent des crottes cubiques.",
    "Les bananes flottent car elles sont moins denses que l'eau.",
    "Certains chats sont allergiques aux humains.",
    "Les grenouilles peuvent régénérer des membres perdus.",
    "Les moustiques sont deux fois plus attirés par le bleu que par les autres couleurs.",
    "Les hiboux ne peuvent pas bouger leurs globes oculaires.",
    "Un jour sur Uranus dure 17 heures et 14 minutes.",
    "La licorne est l'animal national de l'Écosse.",
    "Un escargot peut dormir trois ans.",
    "Les loutres se tiennent la main en dormant.",
    "Les éléphants sont les seuls animaux incapables de sauter.",
    "La crevette mante frappe aussi vite qu'une balle.",
    "Les vaches ont des meilleurs amis.",
  ],
};

// ─── Russian ──────────────────────────────────────────────────────────────────
const russianStrings = {
  ...englishStrings,
  nav: {
    back:     '← Назад',
    hint:     'Подсказка',
    hideHint: 'Скрыть',
    retry:    'Попробовать снова',
    home:     'Главная',
  },
  home: {
    logoTitle:  'Энергия',
    logoSub:    'Закончите на нуле. Посетите каждую клетку.',
    howToPlay:  'Руководство',
    tutorial:   'Обучение',
    support:    'Источник',
    supportSub: 'Github',
    difficulties: {
      easy:   { label: 'Лёгкий 3×3',    sub: 'Базовые плитки' },
      medium: { label: 'Средний 4×4',   sub: 'Замки + направления' },
      hard:   { label: 'Сложный 4×4',   sub: 'Контрольные точки + все типы' },
      brutal: { label: 'Жёсткий 5×5',   sub: 'Всё в большом масштабе' },
    },
  },
  game: {
    idlePrompt:  'Нажмите на любую клетку, чтобы начать',
    stuckBanner: '⛔ Нет допустимых ходов — Отмените или Сбросьте',
  },
  tutorial: {
    title: 'Обучение',
    tooltips: {
      startRule:  'Начните на положительной плитке, чтобы получить энергию.',
      secondRule: 'Вы можете посещать только соседние клетки.',
      thirdRule:  'Каждый ход стоит 1 единицу энергии.',
      fourthrule: 'Пинг указывает ваше местоположение.',
      multiplier: '✕ Плитки-множители умножают вашу текущую энергию',
      drain:      '⬇ Отрицательные плитки расходуют энергию. Будьте осторожны!',
      locked:     '🔒 Заблокированные плитки разблокируются после достаточного числа ходов',
      allTiles:   '✓ Посетите каждую плитку, чтобы завершить головоломку',
      finish:     'Закончите с нулевой энергией для идеального счёта.',
      completed:  '🎉 Отлично! Вы завершили обучение!',
    },
  },
  energyBar: {
    label:          '⚡ ЭНЕРГИЯ',
    movesLabel:     'Ходы:',
    lowEnergyAlert: '⚠️',
    locked:         (movesLeft: number) => `🔒 Осталось ${movesLeft}`,
    unlocked:       '🔓 Разблокировано!',
  },
  controls: {
    undo:       'Отменить',
    reset:      'Сбросить',
    regenerate: 'Новое',
  },
  win: {
    title: [
      "Бинго!",
      "Сетка покорена!",
      "Победа!",
      "Взлёт!",
      "Магическое решение!",
      "Мастер головоломок!",
      "Сетка в огне!",
      "Точно в цель!",
      "Яблочко!",
      "Звёздный игрок!",
      "Отличный ход!",
      "Момент озарения!",
      "Блестящая победа!",
      "Время праздновать!",
      "Чемпион!"
    ],
    subtitle: [
      'Идеальный путь. Нулевая энергия использована мудро.',
      'Безупречно! Энергия не потрачена впустую.',
      'Вы освоили путь без излишков.',
      'Оптимальные ходы, максимальная эффективность!',
      'Вся энергия использована идеально. Отличная работа!',
    ],
    subtitletwo: [
      'Почти идеально. Немного энергии осталось…',
      'Хорошая работа! Но можете ли вы использовать всю энергию?',
      'Хороший путь, хотя немного энергии осталось.',
      'Вы закончили с запасом ходов… можете ли вы улучшить результат?',
      'Немного энергии не использовано. Бросьте себе вызов!',
    ],
    subtitleone: [
      'Энергия растрачена впустую. Попробуйте лучше планировать!',
      'Много неиспользованных ходов. Можете оптимизировать?',
      'Ваш путь неэффективен. Куда делась энергия?',
      'Закончили, но осталось много энергии. Сосредоточьтесь!',
      'Осталось слишком много энергии. Попробуйте ещё раз!',
    ],
    statMoves:  'Время',
    statGrid:   'Сетка',
    statLevel:  'Уровень',
    playAgain:  'Играть снова',
    replay:     'Та же головоломка',
    home:       'Главное меню',
    generate:   'Создать новое',
  },
  howTo: {
    title:        'Как играть',
    letsPlay:     'Играть!',
    tilesSection: 'Типы плиток',
    rules: [
      { icon: '🗺️', text: 'Посетите ',         highlight: 'каждую клетку',              suffix: ' хотя бы один раз.' },
      { icon: '⚡', text: 'Каждый ход ',        highlight: 'стоит 1 энергию',            suffix: ' или больше.' },
      { icon: '🧩', text: 'Иногда вы ',         highlight: 'получаете энергию',          suffix: ', иногда теряете.' },
      { icon: '🚫', text: 'Энергия ',           highlight: 'никогда не бывает отрицательной', suffix: '.' },
      { icon: '🎯', text: 'Закончите с ',       highlight: '0 энергии',                  suffix: ' для идеального счёта.' },
      { icon: '📊', text: 'Лишняя энергия ',    highlight: 'снижает счёт',               suffix: ', но победа есть победа.' },
    ],
    tiles: [
      { icon: '+N',  name: 'Положительная плитка', desc: 'Добавляет энергию при посещении.' },
      { icon: '−N',  name: 'Отрицательная плитка', desc: 'Расходует энергию при посещении.' },
      { icon: '×N',  name: 'Множитель',            desc: 'Умножает вашу текущую энергию на N.' },
      { icon: '🔒',  name: 'Заблокированная плитка', desc: 'Заблокирована до совершения достаточного числа ходов.' },
      { icon: 'in↓', name: 'Входные ворота',        desc: 'Войти можно только с указанного направления.' },
      { icon: 'ex↑', name: 'Выходные ворота',       desc: 'Следующий ход будет принудительно выполнен в указанном направлении.' },
      { icon: '≥N',  name: 'Контрольная точка',     desc: 'Вы должны прийти сюда с не менее чем N единицами энергии.' },
    ],
  },
  generating:   'Генерация',
  funFactTitle: 'Создание требует времени. Вот интересный факт:',
  funFacts: [
    "Мёд никогда не портится.",
    "Бананы — это ягоды, а клубника — нет.",
    "У осьминогов три сердца.",
    "Стая фламинго называется «фламбуанс».",
    "Ленивцы задерживают дыхание дольше, чем дельфины.",
    "Морские выдры держатся за лапки, когда спят.",
    "У коров есть лучшие друзья.",
    "Некоторые черепахи дышат через задний проход.",
    "Экскременты вомбата имеют форму куба.",
    "День на Венере длиннее, чем год на Венере.",
    "Существует вид бессмертной медузы.",
    "Голуби узнают себя в зеркале.",
    "Коалы спят до 22 часов в сутки.",
    "Облако может весить более полумиллиона килограммов.",
    "Акулы появились раньше деревьев.",
    "Лягушки могут замёрзнуть и не умереть.",
    "Бабочки ощущают вкус лапками.",
    "Морские слизни могут поедать себя и восстанавливаться.",
    "Слизистая желудка обновляется каждые 3–4 дня.",
    "Вороны умеют затаивать обиду.",
    "На крыше Верховного суда США есть баскетбольная площадка.",
    "Сердце синего кита размером с автомобиль.",
    "Вомбаты могут бегать со скоростью до 40 км/ч.",
    "Пингвины делают предложение руки и сердца с помощью камешков.",
    "Некоторые муравьи строят живые мосты.",
    "Ленивцы могут поворачивать голову почти на 360°.",
    "Люди разделяют 60 % ДНК с бананами.",
    "«Джиффи» — это 1/100 секунды.",
    "Существует вид гриба, светящегося в темноте.",
    "Морские огурцы выбрасывают внутренние органы, спасаясь от хищников.",
    "Некоторые лягушки выживают в заморозке в течение нескольких лет.",
    "Эйфелева башня летом вырастает на 15 см.",
    "Отпечатки пальцев коалы почти идентичны человеческим.",
    "Дельфины дают имена друг другу.",
    "Существует планета, состоящая из алмаза.",
    "Некоторые черепахи живут более 200 лет.",
    "Морские звёзды отращивают конечности, а некоторые — всё тело целиком.",
    "Чихание разгоняется примерно до 160 км/ч.",
    "Слоны могут «слышать» лапами.",
    "У выдр есть любимый камень для разбивания ракушек.",
    "Морские ежи живут более 100 лет.",
    "Бабочки различают красный, зелёный и жёлтый цвета.",
    "Таракан живёт без головы несколько недель.",
    "Некоторые рыбы ходят по суше.",
    "На Земле деревьев больше, чем звёзд в Млечном Пути.",
    "Летучие мыши всегда поворачивают налево, выбираясь из пещеры.",
    "Акулы чуют каплю крови в олимпийском бассейне.",
    "Один день на Меркурии длится 58 земных суток.",
    "Омары живут более 100 лет.",
    "Ленивцы задерживают дыхание на 40 минут.",
    "Существует вид птицы, имитирующей звук бензопилы.",
    "Некоторые пауки выживают под водой в течение нескольких часов.",
    "Медузы существуют более 500 миллионов лет.",
    "Морские коньки — единственные животные, у которых рожают самцы.",
    "Нос способен запомнить 50 000 различных запахов.",
    "Стая сов называется «парламентом».",
    "Дельфины спят с одним открытым глазом.",
    "Некоторые лягушки меняют цвет, подстраиваясь под окружение.",
    "Кошки издают более 100 различных звуков.",
    "Существует вид муравьёв, порабощающих других муравьёв.",
    "Нить паучьего шёлка прочнее стали.",
    "Фламинго становятся розовыми благодаря еде, которую едят.",
    "У жирафов нет голосовых связок.",
    "Некоторые киты живут более 200 лет.",
    "Ленивцы плавают в три раза быстрее, чем ходят.",
    "Стая ежей называется «прикл» (prickle).",
    "Выдры держатся за лапки, чтобы не уплыть друг от друга.",
    "Свиньи умнее собак.",
    "Желудок вырабатывает новый слой слизи каждые 3 дня.",
    "Некоторые черепахи дышат через клоаку.",
    "Рак-богомол бьёт со скоростью пули.",
    "Слоны оплакивают своих мертвецов.",
    "У морских звёзд нет мозга.",
    "Некоторые рыбы узнают человеческие лица.",
    "Стая хорьков называется «business» (бизнес).",
    "Сердце креветки находится в голове.",
    "Улитки могут спать 3 года.",
    "Под белым мехом у белых медведей чёрная кожа.",
    "Морские коньки меняют цвет для общения.",
    "Влажный нос собаки помогает улавливать молекулы запаха.",
    "Некоторые птицы видят в ультрафиолетовом диапазоне.",
    "Слоны общаются на расстоянии нескольких километров.",
    "Морские звёзды могут выворачивать желудок наружу.",
    "Совы могут поворачивать голову почти на 360°.",
    "Некоторые акулы светятся в темноте.",
    "Язык синего кита весит столько же, сколько слон.",
    "Некоторые лягушки выживают, полностью замёрзнув.",
    "Корова может подняться по лестнице, но не спуститься.",
    "Колибри летают задом наперёд.",
    "Муравьи никогда не спят.",
    "Существует дерево, приносящее более 40 видов фруктов.",
    "Некоторые осьминоги подражают другим животным.",
    "Слоны чуют воду за несколько километров.",
    "Кенгуру не умеют пятиться назад.",
    "Дельфинов наблюдали за тем, как они учат детёнышей пользоваться инструментами.",
    "Мозг потребляет 20 % кислорода всего организма.",
    "Некоторые рыбы выживают вне воды в течение нескольких часов.",
    "Стая ворон называется «murder» (убийство).",
    "Некоторые птицы спят на лету.",
    "У осьминогов синяя кровь.",
    "Вомбаты производят кубические экскременты.",
    "Бананы плавают в воде, потому что они менее плотные.",
    "Некоторые кошки страдают аллергией на людей.",
    "Лягушки могут отращивать потерянные конечности.",
    "Комаров дважды сильнее притягивает синий цвет, чем другие.",
    "Совы не могут двигать глазными яблоками.",
    "День на Уране длится 17 часов 14 минут.",
    "Единорог — национальный символ Шотландии.",
    "Улитка может проспать три года.",
    "Выдры держатся за лапки во сне.",
    "Слоны — единственные животные, которые не умеют прыгать.",
    "Рак-богомол бьёт так же быстро, как пуля.",
    "У коров есть лучшие друзья.",
  ],
};

export const languageStrings: Record<Language, typeof englishStrings> = {
  en: englishStrings,
  es: spanishStrings as unknown as typeof englishStrings,
  fr: frenchStrings as unknown as typeof englishStrings,
  ru: russianStrings as unknown as typeof englishStrings,
};
// For backward compatibility, export the English strings as Strings
export const Strings = englishStrings;